%YAML 1.2
---
# This is an example config file for OS-Installer.
# Place your config under /etc/os-installer/config.yaml for it to be used.
# If a value is not defined, it's default will be used.

# Some strings can have translations by appending an underscore followed by a
# language code, e.g. "name_fr" or "description_pt_BR". These parameters have
# the _LC suffix in their description. No suffix is needed for English.

# Name of the distribution.
# Default: 'Untitled'
distribution_name: 'Stock Linux'

# Whether the installation needs an internet connection.
# Default: yes
internet_connection_required: yes

# A URL/IP address to be used to check for an existing internet connection.
# Default: 'http://nmcheck.gnome.org/check_network_status.txt'
internet_checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'

# Skip the language selection dialog by specifing a language, e.g. 'pt_BR'
# Default: no (No fixed language, not Norwegian)
fixed_language: no

# A selection of languages the installer should present by default.
# Note: For a language to be available, it needs to be provided by the system
# and the installer needs to have a translation into that language.
# Default: ['ar', 'de', 'en', 'es', 'fr', 'ja', 'ru', 'zh']
suggested_languages:
    - 'en'
    - 'fr'


# Show a welcome page after language selection.
#
# logo    string  Optional. Path to a logo (e.g. distribution logo)
# text_LC string  Optional. Welcome text. Translatable.
# usage   bool    Whether to show a welcome page at all.
#
# Default: logo: None, text: None, usage: yes
welcome_page:
    logo    : '/etc/os-installer/icons/stocklinux.png'
    text    : 'Welcome into the install script of Stock Linux!'
    text_fr : 'Bienvenue dans le script d'installation de Stock Linux !'
    usage   : yes

# Minimum disk size needed for the installation (in Gigabyte)
# Default: 5
minimum_disk_size: 20

# Whether to offer setting a disk encryption PIN
# Default: yes
offer_disk_encryption: no

# gnome-initial-setup can handle user and locale setup.
# These settings allow to disable these pages.
#
# Default: skip_user: no, skip_locale: no
skip_user: no
skip_locale: no

# List of software that can additionally be selected for installation.
# Each packages requires all fields to be set.
#
# package         string  Forwarded to the installation script as is.
# suggested       bool    Optional. Whether installation defaults to yes.
# name_LC         string  Name presented to user. Translatable.
#                         If no (English) name is available, it will only
#                         be shown for translated languages.
# description_LC  string  Optional. Description presented to user. Translatable.
# icon_path       string  Optional. Absolute path to icon to be displayed.
#
# Default: [], suggested: False, description: '', icon_path: fallback icon
additional_software:
    - package        : 'firefox'
      suggested      : yes
      name           : 'Firefox'
      description    : 'Popular Web Browser from Mozilla'
      description_fr : 'Navigateur web populaire de Mozilla'
      icon_path      : '/etc/os-installer/icons/firefox.png'
    - package        : 'hyprland'
      suggested      : yes
      name           : 'Hyprland'
      description    : 'Hyprland is a dynamic tiling Wayland compositor that doesn't sacrifice on its looks'
      description_fr : 'Hyprland est un gestionnaire de fenêtres en tuile basé sur Wayland qui ne sacrifie pas l'esthétique'
      icon_path      : '/etc/os-installer/icons/hyprland.png'
    - package        : 'gnome'
      suggested      : yes
      name           : 'Gnome'
      description    : 'Simple and easy to use Desktop Environnement'
      description_fr : 'Environnement de bureau simple et facile d'utilisation'
      icon_path      : '/etc/os-installer/icons/gnome.png'

# List of features that can additionally be selected. Very similar
# to `additional_software`, but meant for more generic features. Can
# be used instead of or in combination with `additional_software`.
#
# feature         string  Forwarded to the installation script as is.
# suggested       bool    Optional. Whether installation defaults to yes.
# name_LC         string  Name presented to user. Translatable.
#                         If no (English) name is available, it will only
#                         be shown for translated languages.
# description_LC  string  Optional. Description presented to user. Translatable.
# icon_path       string  Optional. Absolute path to icon to be displayed.
#
# Default: [], suggested: False, description: '', icon_path: no icon
additional_features:
    - feature        : 'sappy'
      suggested      : yes
      name           : 'Sappy'
      description    : 'Sappy is a CLI package builder.'
      description_fr : 'Sappy est un constructeur de packets en CLI.'
      icon_path      : '/etc/os-installer/icons/sappy.svg'

# Upon failure an option to search for help on the internet is given.
# The url this leads to can be defined here. The squiggly brackets are
# replaced with the os-installer version.
#
# Default: 'https://duckduckgo.com/?q="os-installer {}"+"failed installation"'
failure_help_url: 'https://support.dist.ro/new_issue?q="failed"+"os-installer {}"'

# Certain parts of the installer launch external programs. These can be configured here.
# Note: For calling the command, the string is split up by spaces.
#
# The browser_cmd will be called followed by a url.
#
# Default: browser_cmd: 'epiphany', disks_cmd: 'gnome-disks', wifi_cmd: 'gnome-control-center wifi'
browser_cmd: 'firefox'
disks_cmd  : 'gnome-disks'
wifi_cmd   : 'gnome-control-center wifi'
